### ISSUE TITLE
Research - CI/CD pipeline & automated testing for React Native and Django

### ISSUE THREAD

**Issue by SimonBartonPSU** [Capstone-SS-2020-PDX/Covid-19-MutualAid#12]
# Plan
I will research how we might create an automatic build system as well as an automatic test system.

We want:

- Any time a pull request is opened (or updated with another push), a trigger starts an automatic test suite. Unit tests and regression tests would run so that the sanity check of: did I just break something? Is already answered before folks have to review a pull request.
     - We could have this happen every time we push to branch rather than just PRs if we want.
     - If the test suite fails, it may make sense for the original developer to solve the issue or we may want to hive mind. We will have to think about resolving test failures. If a dev just spent 5 hours writing code, they may need help!

- Any time a pull request is merged, a pipeline is triggered and a complete build of our software is published to some shared location. 
     - This location could be a preconfigured test environment so that our code get deployed but it also can be ran and used/tested by us immediately.
     - This automation seems less important? We might all be building locally? TBD.

# Why is this important
- We need to know that new code does not break our code base. 
- We also need the ability to test our code in a way that is not frustrating or extremely manual.

# Additional Context and Questions
This is just a research issue: once we decide _what_ we want to do, we can create issues for actually creating the stuff.

- Does it make sense to have two separate test suites? One for React Native and one for Django?
     - Or all tests are run anytime a front end or back end change is made?
- What are the best existing tools to automate this? (This may do most of the work for us)
- What tools might specifically help us with automated GUI testing for React Native?

If anyone has additional ideas or suggestions, feel free to comment!

**Comment by EHaake** [comment]
- Ideally, it would be nice to have a single test suite but I'm not sure that is possible.
  - I hope it is though!
- For React Native Building/Test, there is [CRNA - Create React Native App](https://github.com/expo/create-react-native-app) which then deploys to a device using [Expo](https://expo.io/)
  - With npm, you can run `npm start` to run your test suite
  - Can also run `npm run ios` to test the app in the iOS simulator (mac and xcode required)
     - works similarly for android
  - I learned about these from [this article](https://medium.com/@hassanabid/creating-react-native-apps-with-django-rest-api-59e8417865e9)
- I don't know much about Django but I imagine there is a robust testing system for it

**Comment by EHaake** [comment]
- [Here](https://buddy.works/actions/build-react-native-app/integrations/django) is a possibility for CI/CD for our project (buddy.works)
  - Integrates directly with Github via Github Actions
