### ISSUE TITLE
Get User Location in front end when user is registering

### ISSUE THREAD

**Issue by EHaake** [Capstone-SS-2020-PDX/Covid-19-MutualAid#155]
# Plan/Proposed Change
We want to associate location data with postings so that we can filter by radius
Need to get the user's location on the front end and add to the post request

# Why is this important
Need to get the location data from the front-end to the backend

**Comment by SimonBartonPSU** [comment]
Does not work on iOS, found in #268.

**Comment by SimonBartonPSU** [comment]
Closing because  I self-PEBKAC'd.
