### ISSUE TITLE
Fix Title display in Detail Screen

### ISSUE THREAD

**Issue by EHaake** [Capstone-SS-2020-PDX/Covid-19-MutualAid#156]
# Plan/Proposed Change
The titles in the detail view display strangely, not ideal.
They also display differently depending on device size.
Find a way to fix it so that they look reasonably good regardless of length and device size.

# Why is this important
Having details display nicely for the user is important

**Comment by EHaake** [comment]
Title Still needs some work, should be centered and perhaps fontSize could be scaled to length of title
![Screenshot_20200703-185604](https://user-images.githubusercontent.com/20587371/86503051-fac4d300-bd5e-11ea-8dee-5ba354a34b9f.png)

**Comment by SimonBartonPSU** [comment]
I noticed that example shown somehow has 39 characters in the title, which I don't think we will allow.

Still looking at this issue, but with the 25 char limit, worst case is 3 lines of text as is:

![IMG-1647](https://user-images.githubusercontent.com/46763450/86536664-32866480-be9e-11ea-9933-82fb1dc7f8a9.jpg)

![IMG-1648](https://user-images.githubusercontent.com/46763450/86536668-3914dc00-be9e-11ea-80dc-573771f2cfd9.jpg)
