### ISSUE TITLE
Setup Cloud SQL service

### ISSUE THREAD

**Issue by EHaake** [Capstone-SS-2020-PDX/Covid-19-MutualAid#16]
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SimonBartonPSU** [comment]
So Google actually makes it _super_ easy to click the button and spin up an instance. Pick a name, region, Postgres version and boom there's your public IP.

Then you can use the Google cloud console for psql config, or they give you ssh access easily. We will have to think about how we want to firewall psql instances though.

We could do PSU connections only to be safe (accept 131.252.0.0/16), if everyone has VPN access for now. Or if we have security set up well, we can keep them public.
