### ISSUE TITLE
Add 'Report Posting' front end elements

### ISSUE THREAD

**Issue by SimonBartonPSU** [Capstone-SS-2020-PDX/Covid-19-MutualAid#168]
# Plan/Proposed Change
Switch 'Edit' in top right of PostingDetailScreen to a '...' menu that shows one option for now: 'Report post'.

This button will not do anything at first. This is a UI change. Sending the report POST request can occur in a separate task as well as handling the report request on the backend.

# Why is this important
Being able to report / moderate postings is one of our major stretch goals. This issue is one of the first steps to implementing that feature.

**Comment by EHaake** [comment]
Here's a package that might help with the popup: https://www.npmjs.com/package/react-native-popup-dialog
