### ISSUE TITLE
Get basic React Native environment set up

### ISSUE THREAD

**Issue by alexandra-hanson** [Capstone-SS-2020-PDX/Covid-19-MutualAid#20]
Set up the React Native environment on your local machine. For windows users, please reference: https://shift.infinite.red/getting-started-with-react-native-development-on-windows-90d85a72ae65

**Comment by alexandra-hanson** [comment]
Found more recent setup info for Windows: https://codeburst.io/setting-up-development-environment-using-react-native-on-windows-dd240e69f776

**Comment by SimonBartonPSU** [comment]
I ran expo start and got ze QR code!

**Comment by EHaake** [comment]
Got the qr code too!

**Comment by EHaake** [comment]
Everyone got it running. Great job!
