### ISSUE TITLE
Add moderator UI Stack

### ISSUE THREAD

**Issue by EHaake** [Capstone-SS-2020-PDX/Covid-19-MutualAid#232]
# Plan/Proposed Change
If the user's profile's `is_admin` filed is true, then they should seen an additional option in the Drawer Menu for `Admin Tools` or something like that.

This should be a UI Stack that allows them to see flagged postings and potentially a list of user's that have had postings flagged currently or in the past.

The moderator will have the ability to either delete or unflag postings that have been flagged.
The moderator will have the ability to remove user accounts.

# Why is this important
Need some sort of moderator tools to allow removing inappropriate postings and troublesome users.

**Comment by seansisson** [comment]
Perhaps we could use the django admin for this? I will bring it up at today's meeting :)
