### ISSUE TITLE
Terms of Service Page

### ISSUE THREAD

**Issue by EHaake** [Capstone-SS-2020-PDX/Covid-19-MutualAid#242]
# Plan/Proposed Change
After Registration or Profile Creation Screen, present user with a Terms of Service.
User will need to check the 'I agree' section on the page in order to continue.

The text on the Terms of Service page should remove us from any liability, etc and hopefully actually be easy to read, instead of the unintelligible legalese in most Terms of Service pages.

**Comment by KipTheTurtlebear** [comment]
[possible ToS and Privacy Policy](https://getterms.io/g/?product_name=Common+Goods&name=Common+Goods&location=Oregon&effective_date=31+July+2020&language=en-us)
