### ISSUE TITLE
Allow front end to fetch only postings in specific communities

### ISSUE THREAD

**Issue by EHaake** [Capstone-SS-2020-PDX/Covid-19-MutualAid#244]
# Plan/Proposed Change
Instead of just fetching all postings and then filtering on the front end, front end should be able to pass in a list of community id's and the back end should return all postings from communities in that list.

Should be able to send a POST request to `/communities/postings` or something like that and return all postings that are in the array of community id's passed in.

# Why is this important
As the app grows, it will become infeasible to fetch all postings from all communities. The Front End should only be fetching postings from the communities that the user belongs to, by default.

**Comment by seansisson** [comment]
https://django-filter.readthedocs.io/en/stable/
