### ISSUE TITLE
Map Circle on iOS not rendering correctly

### ISSUE THREAD

**Issue by EHaake** [Capstone-SS-2020-PDX/Covid-19-MutualAid#267]
**Describe the bug**
On iOS the circle on the map ignores the styling props for fill and stroke

**To Reproduce**
1. Go to a posting detail screen
2. Look at map
3. Look at circle on map

**Screenshots**
![IMG_3923](https://user-images.githubusercontent.com/20587371/89112953-7d54b700-d41f-11ea-99b9-3acb0191b5b5.PNG)
The circle should be filled in with a low opacity grayish color

**iOS, Android, both?**

**Devices tested:**
 - Device: iPhone 6S Plus

**Additional context**
Looked at thread here for potential fix:

https://github.com/react-native-community/react-native-maps/issues/2698

**Comment by KipTheTurtlebear** [comment]
Can't test on iOS, but making the suggested change of adding:
`// Set native props at every render if iOS`
     ` if (this.circle && Platform.OS == 'ios') {`
     ` this.circle.setNativeProps(this.props);
    }`
before the `return (` to `node_modules\react-native-maps\lib\components\MapCircle.js`

didn't break anything for me on Android, so it's worth a shot on iOS

node_modules is ignored in our project though, so I can't push that change

**Comment by EHaake** [comment]
Yes, that fixes it but not sure how that will incorporate the change into the rest of the project.
