### ISSUE TITLE
Research Django Authentication Library

### ISSUE THREAD

**Issue by EHaake** [Capstone-SS-2020-PDX/Covid-19-MutualAid#47]

**Comment by seansisson** [comment]
Django Authentication classes can be found [here](https://www.django-rest-framework.org/api-guide/authentication/) -- The main separation is how we want to handle users: token, or session auth? Both are provided with django rest auth by default. An additional library that could help for registration is django-rest-auth, also found in the link mentioned earlier, which creates default views for authenticating via token, session, social, etc.
