### ISSUE TITLE
Test Automated App Engine Deployment

### ISSUE THREAD

**Issue by SimonBartonPSU** [Capstone-SS-2020-PDX/Covid-19-MutualAid#52]
# Plan/Proposed Change
I set up an automatic deployment trigger for our Django API. Now I need to actually test the darn thing.

Will perform a "test" push when down time is convenient to verify automated deployment works.

**Comment by SimonBartonPSU** [comment]
Well first test failed due to invalid yaml... Will investigate later.

![image](https://user-images.githubusercontent.com/46763450/82846574-62ede280-9e9e-11ea-8b59-556680b3dd83.png)

**Comment by SimonBartonPSU** [comment]
Tried for a [couple hours](https://github.com/SimonBartonPSU/Covid-19-MutualAid/commits/master) in a forked repo. I can get the deploy to work, but I really want to get migration automated at the same time... or we just resign to doing migrations manually

**Comment by EHaake** [comment]
Hmm, well thanks for trying. Perhaps we'll be able to figure out what the problem with the migrations is but for now I think it's ok
