### ISSUE TITLE
Add navbar component

### ISSUE THREAD

**Issue by seansisson** [Capstone-SS-2020-PDX/Covid-19-MutualAid#67]
Add a generic navbar component for the react frontend to use

This allows us to navigate between different pages on the app

**Comment by SimonBartonPSU** [comment]
Hmm found this https://reactnavigation.org/docs/bottom-tab-navigator/ will try tomorrow

**Comment by SimonBartonPSU** [comment]
On second thought, want to sort out JS dependencies and #78 while I'm at it.
