### ISSUE TITLE
Customize React Navigation Titlebar

### ISSUE THREAD

**Issue by EHaake** [Capstone-SS-2020-PDX/Covid-19-MutualAid#70]
Create the title bar component that should simply display the text prop(s) it receives from its parent (likely the screen component)

**Comment by alexandra-hanson** [comment]
Reference documentation: https://reactnavigation.org/docs/headers/

**Comment by EHaake** [comment]
Since Allie and I discovered that React Navigation supplies it's own title bar, I'm changing this Issue from creating a Separate TitleBar Component to Modifying the provided React-Navigation title bar with styling custom text for each page/route.
