### ISSUE TITLE
Add `make install` target for js, python

### ISSUE THREAD

**Issue by seansisson** [Capstone-SS-2020-PDX/Covid-19-MutualAid#78]
Need a way to install all dependencies for current projects, ideally using `make <language>-install`

**Comment by SimonBartonPSU** [comment]
Well tried for like 3 hours on some throwaway VMs and kinda almost [got there](https://github.com/Capstone-SS-2020-PDX/Covid-19-MutualAid/tree/correct-prereqscript/qa). `make server` works after but stuck with an 'expo not found' on `make js`. After much finagling, still no success.

Starting to wonder how much effort this is worth?

**Comment by EHaake** [comment]
Probably not a huge amount. More of a 'nice to have' than a 'we gotta have this'
