### ISSUE TITLE
Add local.settings.py and move secrets out of git repo

### ISSUE THREAD

**Issue by seansisson** [Capstone-SS-2020-PDX/Covid-19-MutualAid#82]
Several things going on:
- Secrets currently published to github in settings.py
- Need to keep secrets in new file: local.settings.py (not tracked in version control)
Steps:
1. Create local.settings.py and add local.settings.py to .gitignore
2. import settings.py in local.settings.py
3. move secrets from settings.py to local.settings.py
4. Configure docker to run `manage.py --settings=local.settings.py`
4a. Bonus: Add Makefile hook to make local.settings.py

**Comment by SimonBartonPSU** [comment]
We probably ought to set production variables in the app.yaml then keep that guy a secret. Other secrets TBD.

**Comment by robalty** [comment]
Yeah, I'm setting it up that way right now actually. For local operation you'll need to either use the old insecure settings.py or set a matching environment variable on your local instance.
